<a href="https://colab.research.google.com/github/tomonari-masada/course2026-intro2ml/blob/main/05_NumPy_1_%E6%8E%88%E6%A5%AD%E4%B8%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy入門 (1)

* NumPyを説明する前に・・・

## モジュール、パッケージ、ライブラリ
* 参考資料
  * https://zenn.dev/delacroix/articles/e3f62ca001deb0


* モジュール
  * Pythonのファイル(.pyファイル)のこと。
  * `import`文で.pyファイルをインポートすることで、その.pyファイルの中の関数やクラスを使用することができるようになる。
* パッケージ
  * モジュールを複数集めたものです。
  * つまり .pyファイルを複数置いてあるフォルダのようなもの。
  * 言葉としては、次の「ライブラリ」と区別せずに使われることもある。
    * Python Package Index https://pypi.org/
* ライブラリ
  * 複数のパッケージからなるPythonコードの集合体。
  * 標準ライブラリと外部ライブラリがある。
  * 標準ライブラリは、Pythonにはじめからくっついてくるライブラリ。

## mathモジュール
* Pythonでは数学的な処理をするためのモジュールがいくつか用意されている。
  * https://docs.python.org/ja/3.13/library/numeric.html

In [1]:
import math # モジュールやライブラリを使うときの決まった書き方

a = 2.0

In [2]:
b = math.sqrt(a)
print(a, b)

2.0 1.4142135623730951


In [3]:
c = math.exp(a) # eのa乗
print(a, c)

2.0 7.38905609893065


# NumPyライブラリ

* ベクトルや行列を扱える（他にも様々な機能がある）
 * ベクトルどうしの内積
 * 行列とベクトルの積
 * 行列と行列の積
 * 逆行列

* ndarrayという独自のデータ構造を使う
 * ちゃんとコードを書けば高速（ちゃんと書かないと遅い・・・）


## NumPyの配列(ndarray)の作り方

### Pythonのリストから作る

In [4]:
import numpy as np

* 一次元配列

In [5]:
a = np.array([-2.0, 1.0, 3.0])
print(a)

[-2.  1.  3.]


* 二次元配列

In [6]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


* 転置

In [7]:
print(a.T)

[-2.  1.  3.]


In [8]:
print(b.T)

[[1 4]
 [2 5]
 [3 6]]


### ndarrayの演算

In [9]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [10]:
print(a * 3)

[3 6 9]


In [11]:
c = a * 3
print(c)

[3 6 9]


In [12]:
b = np.array([2, 2, 0])
print(b)

[2 2 0]


In [13]:
print(a + b)

[3 4 3]


In [15]:
print(a)
print(b)

[1 2 3]
[2 2 0]


In [14]:
print(a * b)

[2 4 0]


In [18]:
print(a / b) #エラーが出る（どんなエラー？）

[0.5 1.  inf]


/tmp/ipykernel_7115/3077622361.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a / b) #エラーが出る（どんなエラー？）


* ベクトルの内積

In [19]:
print(a)
print(b)

[1 2 3]
[2 2 0]


In [20]:
print(np.dot(a, b))

6


In [21]:
a_list = [1,2,3] # ながさ3
b_list = [2,2,0]
s = 0
for i in range(len(a)):
  s += a_list[i] * b_list[i]
print(s)

6


In [22]:
a_np = np.array(a_list)
b_np = np.array(b_list)
print(np.dot(a_np, b_np))

6


### ndarrayの属性

In [23]:
a = np.array([-2.0, 1.0, 3.0])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
print(a)

[-2.  1.  3.]


In [25]:
print(b)

[[1 2 3]
 [4 5 6]]


* 配列自体のデータ型

In [26]:
print(type(a))

<class 'numpy.ndarray'>


* 配列の要素のデータ型
  * つまり配列の中身のデータ型

In [27]:
print(a.dtype)

float64


* 配列のサイズ

In [28]:
print(a)
print(b)

[-2.  1.  3.]
[[1 2 3]
 [4 5 6]]


In [29]:
print(a.size, b.size)

3 6


* 配列の要素のサイズ

In [ ]:
print(a.itemsize, b.itemsize)

* 次元数

In [30]:
print(a)
print(b)

[-2.  1.  3.]
[[1 2 3]
 [4 5 6]]


In [31]:
print(a.ndim, b.ndim)

1 2


* 形状

In [32]:
print(a.shape, b.shape)

(3,) (2, 3)


### ndarrayの作り方のいろいろ

In [33]:
a = np.arange(10) # Pythonのrangeに似てる
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
for i in range(0, 10, 2):
  print(i)

0
2
4
6
8


In [35]:
b = np.arange(0, 10, 2)
print(b)

[0 2 4 6 8]


In [38]:
x = np.linspace(0, 10, 21) #0以上10以下を6-1等分
print(x)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


* 配列を乱数で埋める

In [44]:
print(np.random.randn()) #正規乱数

-1.3015682825359969


In [45]:
a = np.random.randn(2, 3)
print(a)

[[ 0.79038945  0.38377892  0.18782984]
 [ 2.61476356 -0.42671263  0.49825016]]


In [46]:
b = np.random.randn(3, 4)
print(b)

[[ 0.03875794 -0.56205818 -1.05570835 -0.72335534]
 [-1.43512902  2.0029829  -0.00267851 -1.06009218]
 [ 1.34974908 -1.22830744  1.91385738  0.57725688]]


In [47]:
print(np.dot(a, b))

[[-0.26661525  0.09374498 -0.47596918 -0.87014739]
 [ 1.38624321 -2.93635173 -1.80570503 -1.15143012]]


* 次のセルはエラーになる。
  * なぜ？

In [48]:
print(np.dot(b, a))

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

* 配列をゼロやその他の数値で埋める

In [49]:
a = np.zeros((3,3)) #()で囲む必要あり
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* 問：次のセルの出力結果がなぜそうなるか、説明してみよう。

In [53]:
print(np.dot(b, b))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [57]:
c = np.full((4,6), 7)
print(c)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


## 配列の要素を指定する

### インデックス（添え字）

In [58]:
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


In [59]:
print(a[0])
print(a[1])

1
4


In [60]:
a[3] = 11
print(a)

[ 1  4  7 11 13 16 19]


* 2次元配列の場合

In [61]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [62]:
print(c[0,0])
print(c[0,2])
print(c[1,2])

1
3
6


## ndarrayを高速に扱う工夫
* 要素を個別に取り出して計算したりしない。

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  for i in range(10000000):
    s[i] = x[i] + y[i]
  b = time.time()
  print(b - a)

* 上のセルのように書くより、こう書くほうが良い

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  s = x + y
  b = time.time()
  print(b - a)

## スライシング
* 配列の要素をまとめて扱う。

In [63]:
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


In [64]:
print(a[1:5])

[ 4  7 10 13]


In [65]:
print(a[0:6:2])

[ 1  7 13]


In [69]:
a[0:6:2] = 0
print(a)

[ 0  4  0 10  0 16 19]


In [66]:
print(a[::-1])

[19 16 13 10  7  4  1]


In [67]:
print(a[-2::-1])

[16 13 10  7  4  1]


In [68]:
print(a[-2:1:-1])

[16 13 10  7]


### fancy index

In [ ]:
np.random.seed(1234)
a = np.random.randint(10, size=10)
print(a)

In [ ]:
m = a % 3 == 0
print(m)

In [ ]:
print(type(m))
print(m.dtype)

In [ ]:
b = a[m]
print(b)

### where関数

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)

In [ ]:
m = np.where(a % 2 == 0) #インデックスのtupleを返す
print(m)
print(type(m))

In [ ]:
b = a[m]
print(b)

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)

In [ ]:
m = np.where(a % 2 == 0, 'even', 'odd')
print(m)

In [ ]:
print(a[m == 'even'])

## 配列のコピー

### 配列のビュー
* 中身をコピーするわけではない。

In [ ]:
a = np.array([1, 2, 3])
b = a #ビューを作っている

### リストのコピー

In [ ]:
a = [1, 2, 3]
b = a
b[1] = 22
print(a)
print(b)

In [ ]:
c = a[:] #リストがコピーされる
c[2] = 234
print(a)
print(c)

### ndarrayの場合の`a[:]`
* コピーされるかどうか？

In [ ]:
a = np.array([1, 2, 3])
c = a[:]

In [ ]:
print(id(a) == id(c))

In [ ]:
c[1] = 22
print(a) #変化している

### `copy`メソッド

In [ ]:
a = np.array([1, 2, 3])
d = a.copy() #コピーを作る
print(id(a) == id(d))

In [ ]:
d[2] = 234
print(a) #変化していない

## 配列の形の変更

In [70]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


* NumPyのreshape関数

In [71]:
b = np.reshape(a, (3, 4)) #
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


* 元の配列の中身を変更してみる。

In [72]:
a[3] = - a[3]
print(a)

[ 0  1  2 -3  4  5  6  7  8  9 10 11]


* 注意: reshape関数は配列の中身をコピーしない。

In [73]:
print(b) #中身が変化している!

[[ 0  1  2 -3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


* ndarrayのreshapeメソッド

In [74]:
print(a)

[ 0  1  2 -3  4  5  6  7  8  9 10 11]


In [75]:
c = a.reshape((2,6))
print(c)

[[ 0  1  2 -3  4  5]
 [ 6  7  8  9 10 11]]


# 課題20260525
* 1から1000までの範囲のすべての偶数の和を求める計算を、NumPyの機能を使って書いてみよう。
  * NumPyの配列を使う、NumPyのarangeを使う、などなど。とにかく、何か一つでもNumPyの機能を使ってください。